#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Ejecuta tests de backend
cd backend && npm install && npm test
BACKEND_STATUS=$?
cd ..

# Ejecuta tests de frontend
cd frontend && npm install && npm test
FRONTEND_STATUS=$?
cd ..

if [ $BACKEND_STATUS -ne 0 ] || [ $FRONTEND_STATUS -ne 0 ]; then
  echo "\n❌ Tests fallidos. Push cancelado."
  exit 1
fi

echo "\n✅ Todos los tests pasaron. Realizando push..."
exit 0
